# Generated by Django 3.2.11 on 2022-01-29 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20220129_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='college',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='contact',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='current_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='department',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='docfile',
            field=models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images'),
        ),
    ]
