# Generated by Django 3.2.11 on 2022-01-29 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20220129_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='update_status',
            field=models.CharField(default='No', max_length=15),
            preserve_default=False,
        ),
    ]
