# Generated by Django 3.2.11 on 2022-01-30 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_applicant_update_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='degree',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
