# Generated by Django 3.2.11 on 2022-01-30 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_applicant_degree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='docfile',
            field=models.FileField(blank=True, null=True, upload_to='resume'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics'),
        ),
    ]
