# Generated by Django 3.2.11 on 2022-01-31 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_application_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='gender',
        ),
        migrations.AlterField(
            model_name='company',
            name='image',
            field=models.ImageField(upload_to='company_logo'),
        ),
    ]
