# Generated by Django 3.2.11 on 2022-02-07 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_job_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_profile',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
